server:
    port: 80
    address: 127.0.0.1
    context-path: /
app:
    name: UnitTests
winter:
    application:
        name: UnitTests
        id: UnitTests
        version: 1.0.0-DEV
    namespaces:
        cacheDisabled: true
        cacheTime: 1
    route:
        cacheDisabled: true
        cacheTime: 1

appTest:
    value1: Thor Odinson
    value2: 3450
    value3: true
    value4: 10.98
datasource:
    -   name: defaultDb
        isPrimary: true
        url: "sqlite::memory:"
        username:
        password:
        validationQuery: SELECT 'Databse Connected'
        driverClass: dev\winterframework\pdbc\pdo\PdoDataSource
        connection:
            persistent: true
            errorMode: ERRMODE_EXCEPTION
            columnsCase: CASE_NATURAL
            timeoutSecs: 30
            autoCommit: true
            rowsPrefetch: 100

    -   name: secondaryDb
        url: "mysql:host=localhost;port=3307;dbname=testdb"
        username: root
        password:
        validationQuery: "select curdate() from dual"
        driverClass: dev\winterframework\pdbc\pdo\PdoDataSource
        connection:
            persistent: true
            errorMode: ERRMODE_EXCEPTION
            columnsCase: CASE_NATURAL
            timeoutSecs: 30
            autoCommit: true
            rowsPrefetch: 100

modules:
    - module: "\\test\\winterframework\\modules\\mtk\\MtkModule"
      enabled: true
    - module: "\\test\\winterframework\\modules\\tihrd\\TihrdModule"
      enabled: true
